version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./model.joblib:/app/model.joblib

  streamlit:
    build: .
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - fastapi

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.11.1
    ports:
      - "5001:5000"
    command: mlflow server --host 0.0.0.0 --port 5000
    volumes:
      - ./mlruns:/mlruns